listen_addresses = '*'
port = 5432
max_connections = 20
shared_buffers = 64MB
effective_cache_size = 192MB
work_mem = 2MB
maintenance_work_mem = 32MB
password_encryption = 'scram-sha-256'
huge_pages = off
shared_preload_libraries = 'pg_stat_statements'
timezone = 'UTC'
log_timezone = 'UTC'
log_min_duration_statement = 250
log_connections = on
log_disconnections = on
logging_collector = off
ssl = off
