listen_addresses = '*'
port = 5432
max_connections = 40
shared_buffers = 128MB
effective_cache_size = 512MB
work_mem = 2MB
maintenance_work_mem = 64MB
password_encryption = 'scram-sha-256'
huge_pages = off
shared_preload_libraries = 'pg_stat_statements'
timezone = 'UTC'
log_timezone = 'UTC'
log_min_duration_statement = 250
log_connections = on
log_disconnections = on
logging_collector = off
ssl = off
